### ISSUE TITLE
想问一下协议Apache-2.0相关问题

### ISSUE THREAD

**Issue by wakeupSu** [MinJieLiu/react-photo-view#101]
大佬，查了下这个Apache-2.0，说是要指明所有修改过的文件。有点不太清楚，如果只是当三方库使用，是不是和MIT一样，只有fork后改了代码当新项目发布才需要指明所有修改过的文件

**Comment by MinJieLiu** [comment]
是的

**Comment by wakeupSu** [comment]
> 是的

好的，谢谢回复
