### ISSUE TITLE
Image caption

### ISSUE THREAD

**Issue by shajil-t** [MinJieLiu/react-photo-view#103]
Is there a way we can pass a caption to an image and show when its opened? perhaps somewhere where the counter is displayed?

![image](https://user-images.githubusercontent.com/76836201/163842240-198a996d-8dfc-4c9b-930a-13752f275004.png)

**Comment by MinJieLiu** [comment]
You can use toolbarRender with absolute positioning first, I will add API on Photo later

**Comment by MinJieLiu** [comment]
v1.1.0
Currently you can set `bannerVisible` to false, use `overlayRender` API to customize

**Comment by shajil-t** [comment]
Great, thank you so much :)
