### ISSUE TITLE
Slider sticks when right-click at image

### ISSUE THREAD

**Issue by zhangbenber** [MinJieLiu/react-photo-view#104]
The slider sticks in sliding state after right-click at image (which normally triggers the context menu). You may need to click once again to exit.

右键点击预览状态的图片触发右键菜单之后，移动鼠标会发现画廊会卡在滑动的状态，需要再次点击鼠标才能结束滑动。

Reproduced on react-photo-view@1.0.0 (or https://react-photo-view.vercel.app/ site).

Add these lines in [PhotoBox.tsx:405](https://github.com/MinJieLiu/react-photo-view/blob/master/packages/react-photo-view/src/PhotoBox.tsx#L405) may help.

```diff
function handleMouseDown(e: React.MouseEvent) {
+  if (e.button === 0) {
     e.stopPropagation();
     handleStart(e.clientX, e.clientY, 0);
+  }
 }
```

**Comment by MinJieLiu** [comment]
I'll fix it later

**Comment by MinJieLiu** [comment]
1.1.0
