### ISSUE TITLE
框架报错，无法正常运行

### ISSUE THREAD

**Issue by MaleWeb** [MinJieLiu/react-photo-view#107]
![image](https://user-images.githubusercontent.com/20508968/168406337-ac860c79-a954-46ea-8889-696bb067a750.png)
麻烦看下，如果解决，百思不得其解

**Comment by MinJieLiu** [comment]
如果你跑的是本身的例子的话，包管理器用的是 pnpm。有 pnpm-lock.yaml 可以保持依赖的准确性。
pnpm i 应该没问题
