### ISSUE TITLE
Usage in WebComponents

### ISSUE THREAD

**Issue by konstantinkreft** [MinJieLiu/react-photo-view#109]
First of all, great library :)

Would it be possible to make the target of the react portal in `SlidePortal` configurable instead of hardcoded `document.body`? 
That would make the library usable in web components with a `shadowRoot`.

I'm talking about this line:
https://github.com/MinJieLiu/react-photo-view/blob/9a37f8ff9100a20e0b080c53b71be2ea2cc76843/packages/react-photo-view/src/components/SlidePortal.tsx#L6

Would be happy to work on this.

**Comment by MinJieLiu** [comment]
PR welcome 😀
