### ISSUE TITLE
关于图片预览组件的部分UI建议

### ISSUE THREAD

**Issue by wongchisum** [MinJieLiu/react-photo-view#11]
大佬你好，很荣幸能使用你写的这一款图像预览组件。
使用之前，我是根据photoswipe去二次开发，但是使用体验不尽如人意。
使用你的这个图像预览感觉很方便，能在顶部增加一个工具栏的话就更好了。
希望这个建议可以让组件更友好一些：-）

**Comment by MinJieLiu** [comment]
工具栏按钮比如 全屏，分享？或者我先加个 toolbarRender 的 API，先弄个全屏，分享的话感觉实际业务更相关

**Comment by wongchisum** [comment]
![share](https://user-images.githubusercontent.com/18590315/80462642-930e9800-8969-11ea-8cff-c00ed8e1f3f5.png)
这个是我用photoswipe二次开发的，工具栏补充了下载/旋转/缩放/复位。
因为有一些用户感觉单纯凭鼠标操作不够友好，需要借助工具栏去了解功能

**Comment by MinJieLiu** [comment]
0.5.0
