### ISSUE TITLE
拖拽图片时，不改变mask的透明度

### ISSUE THREAD

**Issue by zuiaiwanqian** [MinJieLiu/react-photo-view#112]
我想实现拖拽图片时不改变mask的透明度，但看文档没有这个方法的回调，也没有参数设置，大佬可以加一个参数吗？感激

**Comment by MinJieLiu** [comment]
只有在拖拽关闭的时候才会修改 透明度，你可以禁用 下拉关闭，就不会有透明度了

**Comment by MinJieLiu** [comment]
嗯，发现了，禁用关闭的时候不应该设置透明度，晚点我改下

**Comment by zuiaiwanqian** [comment]
好的 谢谢大佬，有一个建议：可以设置为一个boolean值吗？开启时就降低，不开启就关闭，不和拖拽关闭有联系

**Comment by MinJieLiu** [comment]
1.2.1
