### ISSUE TITLE
如何使所有的 PhotoView 图片会按照指定顺序提取为一组图片预览画廊？

### ISSUE THREAD

**Issue by skirodev** [MinJieLiu/react-photo-view#118]
如何使所有的 PhotoView 图片会按照指定顺序（例如：图片消息的发送时间顺序）而非默认的运行顺序提取为一组图片预览画廊？

版本：v1.2.2

在一个聊天应用中，当用户进入聊天界面时会先加载一段时间内的历史消息`initialMsgs`，同时向下滑动会触发加载更多的历史消息`earlierMsgs`，由于`earlierMsgs`是在`initialMsgs`之后由用户手动触发请求数据并渲染，导致`earlierMsgs`在画廊中的序号反而比`initialMsgs`更大，如果我希望图片在画廊中按照消息发送时间而非运行时间顺序排列，那么应该怎么做呢？

**Comment by MinJieLiu** [comment]
这种情况可以试试受控的方式，自己设置 images 的顺序
