### ISSUE TITLE
overlayRender如果包含点击事件，会导致index=-1

### ISSUE THREAD

**Issue by jquite** [MinJieLiu/react-photo-view#123]
版本：1.2.2

如题，在overlayRender自定义内容中添加点击事件，事件改变hooks设置的值，会导致index=-1

![微信截图_20220907164122](https://user-images.githubusercontent.com/8909038/188833210-bb44c99c-f6d5-4684-97f7-ce9cece5ee89.png)

代码：[https://github.com/jquite/react-photo-view-example](https://github.com/jquite/react-photo-view-example)

**Comment by MinJieLiu** [comment]
![image](https://github.com/MinJieLiu/react-photo-view/assets/6167727/e5c1fb1b-023b-45c2-aa3c-7eab786f00e3)
key 设置有问题
