### ISSUE TITLE
想咨询下文档站的搜索是如何做的

### ISSUE THREAD

**Issue by Stxr** [MinJieLiu/react-photo-view#133]
我看到这个库的文档站的搜索功能很棒，想请教下是如何做的，用的是什么库呢？
https://react-photo-view.vercel.app/docs/getting-started
感谢。

**Comment by MinJieLiu** [comment]
用的就是 next.js 里面的的一个文档框架。搜索功能也就是一个sdk，下拉的时候有 logo

**Comment by Stxr** [comment]
> 用的就是 next.js 里面的的一个文档框架。搜索功能也就是一个sdk，下拉的时候有 logo

框架是nextra吗? 搜索看起来是离线的，能再请教下sdk的名字吗？想看看是怎么实现的。
感谢。

**Comment by MinJieLiu** [comment]
对 nextra
