### ISSUE TITLE
缩放为何按屏幕比例来的？这个可以调整为按图片大小来吗？

### ISSUE THREAD

**Issue by big-camel** [MinJieLiu/react-photo-view#139]
初步判断是否因为跟左右滑动判断阈值有关？

**Comment by MinJieLiu** [comment]
这是默认的逻辑，图片太大会按照比例缩放到屏幕内，图片太小则会按照图片大小来

**Comment by big-camel** [comment]
大佬终于来了，之前没等到你，我先做了个drag模式了。。。这种效果吧
https://react-image-previewer-example.vercel.app/docs/getting-started#%E6%8B%96%E6%8B%BD%E6%A8%A1%E5%BC%8F

**Comment by MinJieLiu** [comment]
👍 效果不错

**Comment by big-camel** [comment]
> 👍 效果不错

多亏了大佬的代码，站在巨人的肩膀上改起来快。
