### ISSUE TITLE
PhotoSlider

### ISSUE THREAD

**Issue by 273403986** [MinJieLiu/react-photo-view#14]
这个有例子吗？show code 只看见一个<ControlledView />

**Comment by MinJieLiu** [comment]
`PhotoProvider` 也是基于 `PhotoSlider` 封装的

https://github.com/MinJieLiu/react-photo-view/blob/master/src/PhotoProvider.tsx#L77

具体例子 https://minjieliu.github.io/react-photo-view/?path=/story/react-photo-view--%E5%8F%97%E6%8E%A7-photo-slider

**Comment by 273403986** [comment]
单独的一个PhotoSlider,支持自定义工具栏，放大、缩小、旋转吗？
