### ISSUE TITLE
如何获取导航操作发生前的事件回调

### ISSUE THREAD

**Issue by guichun68** [MinJieLiu/react-photo-view#142]
## 问题
我想在用户鼠标点击上一张 或 下一张 按钮时(或键盘操作)拦截该操作，做一些业务性的判断处理，判断处理通过后才放行其操作，请问如何拦截该事件呢？  

## 相关API尝试
我在文档中看到有个onIndexChange 的API，在该事件回调中虽然能通过index来控制不让图片跳转，但页面还是做了刷新，导致用户做的旋转等操作丢失，原因貌似该回调发生在了跳转之后，只是被我强制通过index给拽回原图片而已。

**Comment by big-camel** [comment]
同样的，index 用受控的

**Comment by MinJieLiu** [comment]
这个不如你单独一张图片一个 Provider 来得实在。

**Comment by guichun68** [comment]
好吧，谢谢
