### ISSUE TITLE
Ref conflict with other drag library

### ISSUE THREAD

**Issue by Ardear** [MinJieLiu/react-photo-view#149]
I'm using both `react-photo-view` and `@dnd-kit/sortable` on the same image, such as :

```javascript
const { attributes, listeners, setNodeRef, transform, transition } =
    useSortable({ id: src })

return <PhotoView src={src} >
      <image src={src} ref={setNodeRef} {...listeners}>
    </PhotoView>
```

Both of them need to set ref, which cause the drag library invalid. Although I can add a `div` to fix it, but i think there will be a better solution, such as using [react-merge-refs](https://github.com/gregberge/react-merge-refs)

**Comment by MinJieLiu** [comment]
In fact, we can use the useImperativeHandle API, welcome pr

**Comment by Ardear** [comment]
> In fact, we can use the useImperativeHandle API, welcome pr

I don't think `useImperativeHandle ` is useful. The problem is caused by  
```javascript
// PhotoView.tsx
const originRef = useRef<HTMLElement>(null);

if (children) {
    return Children.only(cloneElement(children, { ...eventListeners, ref: originRef }));
  }

```
The `originRef` will reset the user settings, there doesn't seem to be a way to fix it with `useImperativeHandle`.

**Comment by MinJieLiu** [comment]
```js
useImperativeHandle(children?.ref, () => originRef.current);

```
It works fine. I didn't test it carefully and if there were no bugs I released the version

**Comment by Ardear** [comment]
OK，thanks
