### ISSUE TITLE
touchmove,mousemove等事件绑在window，导致页面其他内容无法滚动

### ISSUE THREAD

**Issue by ly8v** [MinJieLiu/react-photo-view#16]
我最近在实现一个功能，页面打开主内容就是这个大图查看，但是页面自定义了一个分享按钮，点击后会生成一张用于分享的图片，图片比较长，需要滚动，但由于本插件将事件绑定在了window上，导致页面的滚动失效，请问应该如何处理？

**Comment by MinJieLiu** [comment]
是打开了图片预览需要滚动吗？没有打开的时候是没绑定任何事件的，打开的时候也不是 touchmove 事件的问题，而是故意禁止了页面的滚动。因为图片本身就可以滑动预览，避免滚动穿透

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/react-photo-view/blob/master/src/components/SlideWrap.tsx#L14

**Comment by ly8v** [comment]
可能我没有描述清楚，首先从图片列表点击一张图片，然后跳转到详情页，详情页挂载后就立即执行了该组件，但我在这个页面上又自定义了一些其他内容，就是在大图没有关闭的情况下实现其他元素的滚动

**Comment by MinJieLiu** [comment]
你的意思是在大图的背后滚动？这个很显然不合理，大图的背景是黑色的，你也看不到滚动的内容。或者你可以上传个gif 看看效果

**Comment by ly8v** [comment]
![image](https://user-images.githubusercontent.com/37574472/83619347-519f8700-a5be-11ea-8036-db4f83df4116.png)
![image](https://user-images.githubusercontent.com/37574472/83619414-6d0a9200-a5be-11ea-957c-aff5fab594fd.png)
不会搞gif，惭愧。

我截了两张图，第一张是大图页面，第二张是点击分享按钮后，在大图前面插入的一个容器，z-index比大图高。
因为大图在背后，而且滚动被锁，从而导致插入的容器无法滚动

**Comment by MinJieLiu** [comment]
一旦大图在的时候，锁定 body 滚动是必然的，你这个需求可以在浮动在上层的容器上面加个 overflow-y: auto，以便在容器内部滚动。

**Comment by ly8v** [comment]
在PC端是可以用鼠标滚轮和上下方向键控制分享容器的滚动，但移动端触摸的就失效了

**Comment by MinJieLiu** [comment]
不用方向键，div 加个 overflow: auto 也能滚动，并不一定要body 滚动啊

**Comment by ly8v** [comment]
![image](https://user-images.githubusercontent.com/37574472/83705241-01203c00-a647-11ea-91c9-33b5821c7a9e.png)
不是不能滚动，而是touchmove事件被注册在window上，除了大图，其他元素都用不了touchmove了

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/83707609-fa94c300-a64c-11ea-814a-77e41dc64d3e.png)
![image](https://user-images.githubusercontent.com/6167727/83707653-0e402980-a64d-11ea-9154-9a9f31c8aecd.png)
阻止事件冒泡，就可以滚动了

**Comment by MinJieLiu** [comment]
@ly8v 你解决了吗

**Comment by ly8v** [comment]
还没开始弄，我今天在做其他需求，晚上我试试

**Comment by ly8v** [comment]
已经解决了，十分感谢
