### ISSUE TITLE
Open image viewer on button click

### ISSUE THREAD

**Issue by MeesPos** [MinJieLiu/react-photo-view#171]
Is it possible to open the image viewer with a button? I also just want the standard way that you click on an image and then you get it, but I also want a button with which you can open it.

**Comment by MinJieLiu** [comment]
![image](https://github.com/MinJieLiu/react-photo-view/assets/6167727/2ae4dbbc-3897-4909-8fad-da3da2f14500)
Like this?

**Comment by MeesPos** [comment]
> ![image](https://private-user-images.githubusercontent.com/6167727/297236617-2ae4dbbc-3897-4909-8fad-da3da2f14500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Mjc5OTQsIm5iZiI6MTcwNTkyNzY5NCwicGF0aCI6Ii82MTY3NzI3LzI5NzIzNjYxNy0yYWU0ZGJiYy0zODk3LTQ5MDktOGZhZC1kYTNkYTJmMTQ1MDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTI0ODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZiZDc4OGY4YWE1NmIzNmZjYjZjMjA4ZDJlZWFlMjYyMTM5ZTFhODA3ZWIwM2ExYWE2N2Y3NDk2Y2U5MWY1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kVY8-ULWBjWiKgzilHVElsaUrn5NZs-3mlsdZxRfitA) Like this?

Yes, thank you!
