### ISSUE TITLE
默认支持toolbar

### ISSUE THREAD

**Issue by JonathanLee-LX** [MinJieLiu/react-photo-view#18]
添加一个`showToolbar`的属性，来渲染一个默认的toolbar组件，因为在大多数情况下，使用一个默认的toolbar组件来支持缩放，旋转的功能就可以满足需求，而不需要另外在自定义实现。

**Comment by MinJieLiu** [comment]
可以考虑下，本身期望的是默认以最纯粹的方式展现

**Comment by LongYue9608** [comment]
@MinJieLiu 大佬这种用法可以直接增加旋转功能吗，顶不住了，react不熟，不会用
```
<PhotoProvider>
      {photoImages.map((item, index) => (
        <PhotoConsumer key={index} src={item} intro={item}>
          <img src={item} alt="" />
        </PhotoConsumer>
      ))}
    </PhotoProvider>
```

**Comment by MinJieLiu** [comment]
@LongYue9608 
https://github.com/MinJieLiu/react-photo-view/blob/master/example/src/index.tsx#L128
这是例子
