### ISSUE TITLE
😱BUG😱 在Chromium v125以上版本中，图片预览状态下，无法正常进行拖拽/拖动查看图片

### ISSUE THREAD

**Issue by hqw567** [MinJieLiu/react-photo-view#182]
# 😱BUG😱 在Chromium v125以上版本，图片预览状态下，无法正常进行拖拽/拖动查看图片

**Comment by codingdogs** [comment]
设置 img{-webkit-user-drag:none;}

**Comment by hqw567** [comment]
> img{-webkit-user-drag:none;}

这很有效👍
