### ISSUE TITLE
Cannot click the toolbars inside the modal.

### ISSUE THREAD

**Issue by yoouTaro** [MinJieLiu/react-photo-view#185]
I'm currently using the Dialog component from [Shadcn UI](https://ui.shadcn.com/docs/components/dialog), and I'm experiencing an issue where I cannot click on any toolbar elements within the dialog.

**Comment by sahanK** [comment]
How did you resolved this

**Comment by dex1e** [comment]
It`s works for me.

As I understand it, this is because our shadcn portal is blocking the photo portal. 
I hope someone will give more details.

```
 <PhotoProvider
        className="pointer-events-auto">
 </PhotoProvider>
```

**Comment by davidsonsns** [comment]
Thanks @dex1e

**Comment by aardpro** [comment]
好久没有解决，原来如此，大佬牛逼！ @dex1e

**Comment by mudassir-rafiq-007** [comment]
> It`s works for me.
> 
> As I understand it, this is because our shadcn portal is blocking the photo portal. I hope someone will give more details.
> 
> ```
>  <PhotoProvider
>         className="pointer-events-auto">
>  </PhotoProvider>
> ```

Thanks man 🙌  It worked!
