### ISSUE TITLE
如何调整预览图片时的 backdrop 颜色

### ISSUE THREAD

**Issue by syou-yu** [MinJieLiu/react-photo-view#19]
可以支持 调整 backdrop 默认的 defaultOpacity 吗？

**Comment by MinJieLiu** [comment]
后面可以考虑统一配置

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/react-photo-view/releases/tag/v1.0.0-beta.0

**Comment by syou-yu** [comment]
你好。我已收到你的邮件。谢谢。
—————————————————
黄镜明
