### ISSUE TITLE
PhotoView__PhotoBox样式中的width: 0会导致预览时图片出不来

### ISSUE THREAD

**Issue by toulondu** [MinJieLiu/react-photo-view#24]
index.css中
```
.PhotoView__PhotoBox {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 0;
  height: 0;
}
```
预览时，图片外层的div用的这个class，width为0导致无法显示。

**Comment by MinJieLiu** [comment]
为什么要将它设置成0呢，图片在没加载完成的时候是不显示的

**Comment by meitingshuoguo** [comment]
也遇到了在windows下的QQ浏览器，还有mac下的Safari浏览器，有时候不能正确显示图片。
官方的例子在mac的Safari的网络中设置为忽略缓存的情况下，每次都是重新请求后，也不能正确显示图片了

https://github.com/MinJieLiu/react-photo-view/blob/master/src/PhotoView.less
我也不明白这里你为什么要将这个宽高都设置为0呢。

**Comment by MinJieLiu** [comment]
这里设置成0，意味着在加载时不显示图片，加载成功后会重新设置它的宽高。用的是 new Image()。
欢迎pr

**Comment by meitingshuoguo** [comment]
> 这里设置成0，意味着在加载时不显示图片，加载成功后会重新设置它的宽高。用的是 new Image()。
> 
> 欢迎pr

我看最终的效果，图片是设置了宽高的，但是图片的父元素，也就是上面这个元素的宽高还是0的。

**Comment by liu333333** [comment]
> index.css中
> 
> ```
> .PhotoView__PhotoBox {
>   display: flex;
>   justify-content: center;
>   align-items: center;
>   width: 0;
>   height: 0;
> }
> ```
> 
> 预览时，图片外层的div用的这个class，width为0导致无法显示。

我也碰到这个问题，两个子应用同时使用这个插件去预览，第一个应用总是没问题的，第二个应用就会出现展示的问题，也是出现了这个样式
