### ISSUE TITLE
点击蒙层关闭会事件穿透

### ISSUE THREAD

**Issue by JASON-SW** [MinJieLiu/react-photo-view#26]

**Comment by ssgluffy** [comment]
我也遇到同样的问题了，你那边有解决了吗？

**Comment by ChenYingbo** [comment]
这个问题  有啥好的解决方案吗  我这边也遇到了

**Comment by MinJieLiu** [comment]
@ChenYingbo 还存在此类问题吗

**Comment by yutingting945718425** [comment]
我也遇到同样的问题了,当在图片遮层上面关闭图片预览时，会发生事件穿透现象，图片再次被打开预览

**Comment by MinJieLiu** [comment]
@yutingting945718425 最新版本依然存在此问题？

**Comment by yutingting945718425** [comment]
是的，目前移动端存在

**Comment by yutingting945718425** [comment]
目前使用的版本好为@1.0.0-beta.4

**Comment by MinJieLiu** [comment]
@yutingting945718425 有复现步骤吗，或者录个屏

**Comment by yutingting945718425** [comment]
有例子 怎么发你看看呢

**Comment by MinJieLiu** [comment]
https://react-photo-view.vercel.app/#%E5%85%B3%E4%BA%8E

最后有个码，加我好友

**Comment by MinJieLiu** [comment]
`PhotoSlider` 新增 API `afterClose` ,可以以此作为隐藏关闭判断，避免无动画引起穿透问题

**Comment by liangbus** [comment]
目前使用的 1.2.1 版本，也仍有穿透问题

**Comment by MinJieLiu** [comment]
@liangbus 可以详细描述下？

**Comment by liangbus** [comment]
@MinJieLiu 我用的是 PhotoSlider 组件，在移动端浏览器（电脑端 Chrome 模拟器也会出现）用的时候，点击蒙层会点到最底下页面的元素，然后就会触发一些别的事件

（BTW，请教个事情， slider 预览的时候是否有提供图片加载的过渡状态呢？目前看到提供 loading 的 element 好像只是组件显示时触发，有时候图片加载比较慢时，会空空的。）

感谢大佬回复

**Comment by MinJieLiu** [comment]
也无需常驻，有个 afterClose 可以回调

**Comment by liangbus** [comment]
@MinJieLiu 另外，是否能考虑下预览图加载过程中的 Loading 效果呢？

**Comment by MinJieLiu** [comment]
默认带一个 loading 图标，可以自定义
