### ISSUE TITLE
ios系统下图片不支持滑动左右切换

### ISSUE THREAD

**Issue by uouin** [MinJieLiu/react-photo-view#3]
安卓没问题，ios系统下图片不支持滑动左右切换，微信和浏览器都是这样，是需要额外配置什么么

**Comment by MinJieLiu** [comment]
貌似在 ios chrome 中没问题，可能是 safari 的缩小手势导致的，等会我看看

**Comment by MinJieLiu** [comment]
Mac OS、iOS 在最近不区分移动和桌面平台导致的
