### ISSUE TITLE
切换图片被放大的图片不重新渲染

### ISSUE THREAD

**Issue by zemelLeong** [MinJieLiu/react-photo-view#37]
https://codesandbox.io/s/wonderful-ellis-mdd2p

**Comment by MinJieLiu** [comment]
欢迎 pr

**Comment by zemelLeong** [comment]
给consumer加个key似乎就可以了
https://codesandbox.io/s/wonderful-ellis-mdd2p
图片是原本的代码
![image](https://user-images.githubusercontent.com/26835087/96603577-bae22580-1326-11eb-9698-fec274ac712d.png)

**Comment by MinJieLiu** [comment]
现已支持
