### ISSUE TITLE
你好，是否可以考虑下在顶部的自定义工具栏增加放大和缩小图片的功能，谢谢

### ISSUE THREAD

**Issue by zhuibo66** [MinJieLiu/react-photo-view#39]
我使用的是PhotoSlider这个组件，看下toolbarRender这个属性并没有返回对应的图片dom，这样就没有办法直接操作了，所以希望可以增加个在工具栏也可以放大图片的功能，谢谢

**Comment by MinJieLiu** [comment]
有空可以加一下，欢迎pr
