### ISSUE TITLE
能否添加图片旋转甚至裁剪的功能

### ISSUE THREAD

**Issue by WangBin8467** [MinJieLiu/react-photo-view#4]
考虑到目前现有的react图片预览控件都很少有这个功能，或者有的都不好用，作者能否扩展支持一下图片旋转甚至裁剪，这些在预览中对能够图片操作的功能，谢谢！

**Comment by MinJieLiu** [comment]
为了能在移动端更好地使用，并保持更小的尺寸，没打算添加太多的功能。图片旋转功能会转涉及到很多 case，有时间再看怎么更好实现。

**Comment by MinJieLiu** [comment]
0.5.0
