### ISSUE TITLE
如何支持自定义渲染video标签呢?

### ISSUE THREAD

**Issue by youdianfan** [MinJieLiu/react-photo-view#43]
如何支持自定义渲染video标签呢?

**Comment by MinJieLiu** [comment]
目前还不支持

**Comment by youdianfan** [comment]
![1](https://user-images.githubusercontent.com/27018910/109903556-e31b6100-7cd6-11eb-9094-a11c37857168.jpg)
![2](https://user-images.githubusercontent.com/27018910/109903562-e44c8e00-7cd6-11eb-94f1-eaa25238e2b2.jpg)
![3](https://user-images.githubusercontent.com/27018910/109903564-e4e52480-7cd6-11eb-9641-b3da16516699.jpg)

**Comment by youdianfan** [comment]
通过源码修改增加了type字段,在Photo函数里做了判断处理,进行渲染
![image](https://user-images.githubusercontent.com/27018910/109903731-1f4ec180-7cd7-11eb-8921-17f5d3cc375e.png)

**Comment by youdianfan** [comment]
可以考虑增加此操作,我的需求是这样的
![image](https://user-images.githubusercontent.com/27018910/109903879-5de47c00-7cd7-11eb-9107-321168e44557.png)

**Comment by youdianfan** [comment]
感谢您的回复,插件很棒!

**Comment by MinJieLiu** [comment]
可以发个pr @youdianfan 😊

**Comment by Hemuxue** [comment]
我也遇到了需要查看视频的需求，期待解决
