### ISSUE TITLE
放大和缩小按钮

### ISSUE THREAD

**Issue by HackerBoy856** [MinJieLiu/react-photo-view#45]
@MinJieLiu 你好，我看例子上面是有放大和缩小按钮的，但是我没有找到对应代码，能看看怎么实现的不

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/react-photo-view/blob/master/example/src/index.tsx#L111

@HackerBoy856

**Comment by HackerBoy856** [comment]
@MinJieLiu 你好，该代码块我只看到全屏和旋转，并没有看到放大和缩小按钮的，
![image](https://user-images.githubusercontent.com/30853529/111932826-3d9b2680-8af9-11eb-9ffd-c33075ad544f.png)
我希望看到这个按钮的代码，感谢

**Comment by MinJieLiu** [comment]
看错了，放大缩小按钮需要自己加上去的，调用里面的 api 即可实现

**Comment by Silious** [comment]
> 看错了，放大缩小按钮需要自己加上去的，调用里面的 api 即可实现

请问一下放大缩小是调哪个api呢,我这边看只有这些
![image](https://user-images.githubusercontent.com/22768575/115494657-aca2a100-a298-11eb-9033-5f01dd8afe9e.png)

**Comment by MinJieLiu** [comment]
目前好像并没有导出方法😂，要不你可以发个 pull request？我目前没有时间改这块。

**Comment by HackerBoy856** [comment]
> > 看错了，放大缩小按钮需要自己加上去的，调用里面的 api 即可实现
> 
> 请问一下放大缩小是调哪个api呢,我这边看只有这些
> ![image](https://user-images.githubusercontent.com/22768575/115494657-aca2a100-a298-11eb-9033-5f01dd8afe9e.png)

你可以用上下滚动来放大，鼠标放哪里就放大哪里，挺好用的

**Comment by Silious** [comment]
> 目前好像并没有导出方法😂，要不你可以发个 pull request？我目前没有时间改这块。

您好 已提交pr https://github.com/MinJieLiu/react-photo-view/pull/49

**Comment by HackerBoy856** [comment]
> > 目前好像并没有导出方法😂，要不你可以发个 pull request？我目前没有时间改这块。
> 
> 您好 已提交pr #49
👍！
