### ISSUE TITLE
引入样式会影响到ant-design-mobile Picker组件动画

### ISSUE THREAD

**Issue by tong233** [MinJieLiu/react-photo-view#5]
Picker出现动画本来是slide-up变成了zoom，注释掉import 'react-photo-view/dist/index.css'就好了，麻烦看下，谢谢。

**Comment by MinJieLiu** [comment]
ok，我试试

**Comment by MinJieLiu** [comment]
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-mobile-modal-glgow)

↑ 我复现不了，你可以提供 demo 吗

**Comment by tong233** [comment]
我也复现不了，我是这样使用的antd-mobile的，https://mobile.ant.design/docs/react/use-with-create-react-app-cn，没有额外引入antd-mobile的css，然后我的项目也试了一下引入antd-mobile的css也正常了，但不能这么做，会覆盖自定义主题

**Comment by MinJieLiu** [comment]
行，我试试 用变量方式

**Comment by MinJieLiu** [comment]
@tong233 https://github.com/MinJieLiu/react-app-antd-mobile

你可以 clone 下来看看，依然正常

**Comment by tong233** [comment]
@MinJieLiu 我好像找到原因了，用 cssnano压缩css代码就能复现。。你看栗子我的PR

**Comment by MinJieLiu** [comment]
我感觉是 cssnano 的问题，因为我无论怎样改 keyframes 的名字，结果都造成 Picker 应用这个动画

**Comment by MinJieLiu** [comment]
配置里面别开高级模式就没问题

**Comment by tong233** [comment]
> cssnano 配置里面别开高级模式就没问题

嗯，可以了。万分感谢。
