### ISSUE TITLE
每次点击预览，每次都会请求两次相同的图片资源，这个是否能优化？

### ISSUE THREAD

**Issue by CHANCCCZQ** [MinJieLiu/react-photo-view#6]
每次点击预览，每次都会请求两次相同的图片资源，这个是否能优化？

githug无法上传图片，作者可以自己去查看一下network就知道了，我点了三次大图预览，请求了六次同样的资源，其实按道理，请求最多两次就能满足了吧，一次是小图，一次是点击大图。

**Comment by MinJieLiu** [comment]
我重复切换了好几次，都只有预先的图片列表的请求啊
![image](https://user-images.githubusercontent.com/6167727/79094777-29986200-7d8b-11ea-8f56-1fe2170f0ebb.png)

**Comment by MinJieLiu** [comment]
你是不是引入图片的时候 webpack 给你做了 base64 的转化？

**Comment by CHANCCCZQ** [comment]
![image](https://user-images.githubusercontent.com/22274839/79100510-4340a600-7d99-11ea-8e04-399abdafe14f.png)
可是。。。我这里看到的，我点了五次，刚好图片资源加载了十次哎。。

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/79113403-6ed08a00-7db3-11ea-81e5-19f714338ab7.png)
我这里永远只有8个请求

**Comment by MinJieLiu** [comment]
我换了好几台电脑试了都是这样

**Comment by little-buddy** [comment]
@MinJieLiu 那是因为它设置了 Disable cache，做了懒加载的操作在dis cache 下都会请求2次的，肉鸡问题😂

**Comment by MinJieLiu** [comment]
果然 Disable cache 后是这样，这也仅限调试才会 Disable cache
