### ISSUE TITLE
对于受控 PhotoSlider里面的图片 item 类型明originRef是没有作用的

### ISSUE THREAD

**Issue by zhuibo66** [MinJieLiu/react-photo-view#60]
看了下源码里面，在PhotoSlider这个组件里面，是没有用到传进来的originRef字段的

![image](https://user-images.githubusercontent.com/69130137/125150028-43cc1600-e16f-11eb-897e-d441b930d2bf.png)

**Comment by MinJieLiu** [comment]
src/PhotoConsumer.tsx

看这个例子

**Comment by zhuibo66** [comment]
> src/PhotoConsumer.tsx
> 
> 看这个例子

你好，这个列子有看过哦，所以，我在开头说的是【受控 PhotoSlider】里面，图片 item 类型没有originRef

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/125447215-b15fb35f-8ab0-4ea6-b77e-619790833ed7.png)
![image](https://user-images.githubusercontent.com/6167727/125447228-47ec7b5d-c0e1-497e-9c43-726ebe35865e.png)
@zhuibo66
