### ISSUE TITLE
PhotoSlider 双击缩放、双指缩放失效

### ISSUE THREAD

**Issue by yume-chan** [MinJieLiu/react-photo-view#64]
### 代码：

https://codesandbox.io/s/photo-view-zoom-lro5h?file=/src/App.js

### 重现步骤：

1. 点击“打开 PhotoSlider”按钮
2. 双击图片

### 预期行为：

图片放大

### 实际行为：

图片移动，但是不放大

0.5.2 版本正常，0.5.3 版本开始有问题

**Comment by SolidZORO** [comment]
对，我在 Android 的 WebView 中复现了这个问题，疑似 `0d4ab356610c59d4ad5c79eb441c9368954ec7d1 feat: 提供放大缩小API` 这个 commit 导致，0.5.2 还是正常的。

**Comment by MinJieLiu** [comment]
晚点我看看

**Comment by MinJieLiu** [comment]
0.5.6
