### ISSUE TITLE
vue3版本的实现

### ISSUE THREAD

**Issue by NameWjp** [MinJieLiu/react-photo-view#70]
非常喜欢你的组件，但我平时使用 vue 比较多，出于学习和自用参考你的代码使用 vue3 实现了一版，功能基本相同，地址在这里：[https://github.com/NameWjp/vue3-photo-preview](https://github.com/NameWjp/vue3-photo-preview) 希望可以帮到同样需要 vue 版本的人，如果你不介意的话后续我可以放到 npm 供其他人使用。

**Comment by MinJieLiu** [comment]
👍👍👍
