### ISSUE TITLE
偶现crash Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by petrus-hanks** [MinJieLiu/react-photo-view#73]
> TypeError: Cannot read properties of undefined (reading 'key')
(anonymous function)
src/PhotoSlider.tsx:420
  417 | const realIndex = photoIndex === 0 ? photoIndex + index : photoIndex - 1 + index;
  418 | return (
  419 |   <PhotoView
> 420 |     key={item.key ? item.key + item.src : realIndex}
      | ^  421 |     src={item.src}
  422 |     intro={item.intro}
  423 |     onReachMove={this.handleReachMove}
View compiled
(anonymous function)
src/PhotoSlider.tsx:412
  409 | {images
  410 |   .slice(
  411 |     // 加载相邻三张
> 412 |     Math.max(photoIndex - 1, 0),
      | ^  413 |     Math.min(photoIndex + 2, imageLength + 1),
  414 |   )
  415 |   .map((item: dataType, index) => {
View compiled
VisibleAnimationHandle
src/components/VisibleAnimationHandle.tsx:56
  53 |   }
  54 | }, [visible]);
  55 | 
> 56 | return children({
     | ^  57 |   photoVisible,
  58 |   showAnimateType,
  59 |   originRect,

**Comment by MinJieLiu** [comment]
v1.0.0-beta.0
