### ISSUE TITLE
图片无法预览

### ISSUE THREAD

**Issue by eightHundreds** [MinJieLiu/react-photo-view#76]
在PhotoConsumer的handleTouchStart和handleTouchEnd

在个别机型中, 对于一次touch事件,touchStart接收到的`clientX, clientY`与touchEnd的不一致. 所以导致预览没触发

**Comment by eightHundreds** [comment]
Galaxy S9
OneUI 1.0
Android 9.0

**Comment by MinJieLiu** [comment]
欢迎pr

**Comment by MinJieLiu** [comment]
1.0.0
