### ISSUE TITLE
在移动端 图片默认预览的scale太小

### ISSUE THREAD

**Issue by helixs** [MinJieLiu/react-photo-view#77]
我在移动端浏览器或者chrome模拟移动端打开预览，750*1200的图片，展示的默认宽度只有屏幕的一半，需要手动放大显示，我看到img 标签的 scale为0.5-0.6，我觉得应该0.8-0.9左右才合适，暂未发现原因。

**Comment by MinJieLiu** [comment]
图片要么上下适应，要么左右适应，按照比例最大的方向为主的

**Comment by helixs** [comment]
嗯 我知道呀电脑端浏览器没啥问题 ，就移动端出问题了，宽高都没撑满。

**Comment by MinJieLiu** [comment]
有复现的图片吗，或者例子上面的图片能复现吗

**Comment by lisirgo** [comment]
可能是全局img样式导致的，尝试把img宽高属性设置为auto

**Comment by helixs** [comment]
@lisirgo 果然和你说的一样，img标签宽度100%，我定义img 样式` max-width: none`;就好了。谢谢。

**Comment by lisirgo** [comment]
> @lisirgo 果然和你说的一样，img标签宽度100%，我定义img 样式` max-width: none`;就好了。谢谢。

你高兴的太早了，我又发现了另一个问题，就是在ios手机下，预览jpg格式图片放大的时候，会导致webview崩溃....目前还没有好的解决办法....

**Comment by lisirgo** [comment]
你高兴的太早了，我又发现了另一个问题，就是在ios手机下，预览jpg格式图片放大的时候，会导致webview崩溃....目前还没有好的解决办法....@helixs

**Comment by lisirgo** [comment]
@helixs 不过这个问题并不是插件的问题，我尝试了几个插件都有同样的问题，初步排查应该是ios手机兼容性的问题，目前我只能让后端同事处理图片格式了，好头痛.....

**Comment by helixs** [comment]
@lisirgo 我这里适配的是浏览器和微信公众号，暂时还没发现，我用的Android，等测试去测吧

**Comment by helixs** [comment]
@lisirgo 我也遇到了，卧槽，咋搞。

**Comment by MinJieLiu** [comment]
@helixs 给个复现的demo看看？

**Comment by helixs** [comment]
@MinJieLiu 不是你的库有问题，我的场景是html2canvas 把element生成为图片，然后保存到本地。在Ios15的版本会出问题。原因我已经知道了。是字体的问题，判断agent如果是ios15就把所有字体设置为`PingFang`
