### ISSUE TITLE
移动端图片预览,放大或者缩小后关闭,再次打开,还是之前放大缩小的状态

### ISSUE THREAD

**Issue by xujaibo** [MinJieLiu/react-photo-view#78]
移动端图片预览,放大或者缩小后关闭,再次打开,还是之前放大缩小的状态,能否加一个配置项,支持是否保持预览后的放大或者缩小的状态

**Comment by MinJieLiu** [comment]
可以，欢迎发pr

**Comment by xujaibo** [comment]
> 可以，欢迎发pr

你好,目前有这个配置项了吗?

**Comment by xujaibo** [comment]
> 可以，欢迎发pr

我这边项目当下来,简单修改了一下,就是我图片圈起来的部分加一下重置缩放的值就行了,大佬可以看看能不能优化下
![image](https://user-images.githubusercontent.com/45301701/147448902-9073973c-c76f-486a-92a8-d96f863290ee.png)

**Comment by MinJieLiu** [comment]
@xujaibo 按道理应该加个参数支持在动画关闭之后，重置一下所有状态，不只是 scaleMap

**Comment by xujaibo** [comment]
> @xujaibo 按道理应该加个参数支持在动画关闭之后，重置一下所有状态，不只是 scaleMap

对的,这样会比较好一些,我这个只是简单的一个解决办法.大佬空了可以优化一下,哈哈哈

**Comment by xujaibo** [comment]
> @xujaibo 按道理应该加个参数支持在动画关闭之后，重置一下所有状态，不只是 scaleMap
我看了目前市面上的这种,基本上图片预览关闭后都会重置所有的状态,这个配置加不加无所谓,像旋转,缩放这种状态都重置一下就好啦

**Comment by MinJieLiu** [comment]
v1.0.0-beta.0
