### ISSUE TITLE
预览加载原图进行放大的时候会导致图片模糊

### ISSUE THREAD

**Issue by little-buddy** [MinJieLiu/react-photo-view#8]
初步看起来是 transform -> scale 的方式会导致图片失真
这里的图片缩放是否考虑用 width/height 实现缩放来处理？

**Comment by MinJieLiu** [comment]
使用 transform:
![image](https://user-images.githubusercontent.com/6167727/79872237-213dc800-8418-11ea-87d5-29486bd5f793.png)


使用 width/height:
![image](https://user-images.githubusercontent.com/6167727/79872318-3d416980-8418-11ea-85ac-c9fade8d3dfc.png)

放到最大，两者看起来没什么差别

**Comment by little-buddy** [comment]
@MinJieLiu 
作者给出的例子图片只有528b，所以看起来会无差
如果你打开的是一张 8M 的高清图片，你就会明白为什么要放弃 scale

还有
    很好奇作者的项目是部署在哪里的，即使科学上网打开的速度还是很慢，愁人😂

**Comment by MinJieLiu** [comment]
我试了10M的图片，依然很清晰, 图片在 github 上

**Comment by little-buddy** [comment]
微信手机里打开，scale的放大是会失真的。作者的尝试应该是初始的图片展示就比较大吧。
还有，我的pr那样改会造成 动画闪动吗？我这边怎么没发生？

**Comment by little-buddy** [comment]
目前验证到，android手机似乎没这个问题，而iOS是存在的且不同机型表现也不太一样

**Comment by fubd** [comment]
放大的时候会变模糊 然后会很快变清晰 Android上也有这个问题 via浏览器

**Comment by ximouzhao** [comment]
嗯，ios放大的时候严重模糊，不管是safari还是chrome

**Comment by houxd1992** [comment]
请问这个问题目前有好的解决方案了么

**Comment by MinJieLiu** [comment]
@houxd1992 目前还没有，等下个版本，我会重构下

**Comment by tomtang1122** [comment]
点击图片关闭（photoClosable）时，感觉会有延迟

**Comment by chuyun** [comment]
> @houxd1992 目前还没有，等下个版本，我会重构下

问题能先解决下么？

**Comment by MinJieLiu** [comment]
0.5.7
