### ISSUE TITLE
预览图片被缩小了0.5倍

### ISSUE THREAD

**Issue by w611363303798** [MinJieLiu/react-photo-view#82]
之前用的0.4版本是好的，升级到0.5.7就坏了。
通过开发者工具查看是添加了scale(0.5)的问题
![image](https://user-images.githubusercontent.com/24557962/147218807-49877314-11d2-44f9-bc5d-a2e493e48958.png)

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/147238275-a35376a4-fcdf-4de8-b1e3-36786ed133d1.png)
demo 里面看着是好的，可以提供一个出问题的仓库么？

**Comment by w611363303798** [comment]
抱歉，是我自己的问题。img被公共样式污染了
