### ISSUE TITLE
可配置的放大倍数

### ISSUE THREAD

**Issue by mgu-x** [MinJieLiu/react-photo-view#83]
目前这个PhotoSlider是否支持自己定义图片的放大倍数，我看这个放大的倍数默认都是1

**Comment by MinJieLiu** [comment]
欢迎 pr

**Comment by mgu-x** [comment]
这个代码拉下来有问题，yarn 安装依赖报错。

[!] Error: Package subpath './package.json' is not defined by "exports" in /xxx/react-photo-view/node_modules/tslib/package.json

**Comment by mgu-x** [comment]
我想知道node的版本，或者该如何配置才可以让项目运行起来

**Comment by MinJieLiu** [comment]
更新了下，再试试

**Comment by mgu-x** [comment]
中午尝试了下，可以运行
