### ISSUE TITLE
移动端ios点击大小为400k以上图片预览页面崩溃重载，机型iphone7 Plus ,系统14；机型iphone6s Plus ,系统12;iphone13 pro，系统15.0；均会出现此问题

### ISSUE THREAD

**Issue by caomeibuaichibaicai** [MinJieLiu/react-photo-view#85]

**Comment by MinJieLiu** [comment]
也就是例子中大部分图片都有问题？

**Comment by MinJieLiu** [comment]
我升级到15试试

**Comment by caomeibuaichibaicai** [comment]
storybook中的 在线例子，我在手机上确实没有出现崩溃问题。。但是我是本地react项目安装最新版本的包，在大部分苹果手机上都出现了400k以上大的图片预览时，页面崩溃然后重新载入的问题；图片不是我本地项目static资源，是外链展示的，会不会跟这个有关系

**Comment by july-12** [comment]
same!!

**Comment by MinJieLiu** [comment]
@caomeibuaichibaicai 可否搞个远程的资源在 sandbox 看看例子

**Comment by july-12** [comment]
我昨天试了一下，在example的中用一张2.6M的图片替换1.png，然后用一台ios 14系统的iphone x能复现问题

跟了一下代码，主要原因 `Photo.tsx` 组件中 传给img标签style导致 
![image](https://user-images.githubusercontent.com/920487/148157507-59476f58-acda-4dc1-bea0-b3db63932cf4.png)

google 一圈说是得([here](https://stackoverflow.com/questions/30128587/ios-safari-transition-transform-not-working)) `-webkit-transition: -webkit-transform ` 但没起作用，应该还是图片尺寸太大导致的某些底层愿意

我尝试不传这个样式，然后直接用 width/height 替换  naturalWidth/naturalHeight 问题就解决了
![image](https://user-images.githubusercontent.com/920487/148157802-849deabb-0022-4caa-b77f-fbe451650032.png)

我看到还是有动画的，效果也差不多了

**Comment by MinJieLiu** [comment]
接下来抽个空修一下

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/react-photo-view/releases/tag/v1.0.0-beta.0
