### ISSUE TITLE
<WithToolbar />这个组件怎么弄的？

### ISSUE THREAD

**Issue by chenzhengWin** [MinJieLiu/react-photo-view#90]
https://minjieliu.github.io/react-photo-view/?path=/docs/react-photo-view--%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E5%85%B7%E6%A0%8F
要实现放大缩小，旋转等功能效果，
自定义工具栏在example中，无法直接引用？

**Comment by MinJieLiu** [comment]
那是个例子，你可以拷贝里面的代码，默认是不导出这些功能的
