### ISSUE TITLE
点击放大之后切换图片回来还是放大状态

### ISSUE THREAD

**Issue by bugs666** [MinJieLiu/react-photo-view#92]
点击放大之后切换图片回来还是放大状态，这个问题大佬能帮忙优化下嘛，我把代码down下来了，自己改感觉有点费劲，，，

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/react-photo-view/releases/tag/v1.0.0-beta.0

刚重构完，这个功能会考虑下

**Comment by MinJieLiu** [comment]
1.0.0-beta.8
