### ISSUE TITLE
npm install之后还是0.5.7版本，指定v1.0.0-beta.0报错No matching version

### ISSUE THREAD

**Issue by chenzhengWin** [MinJieLiu/react-photo-view#94]
1.  
+ react-photo-view@0.5.7
added 2 packages from 4 contributors in 6.755s

2. npm install react-photo-view@v1.0.0-beta.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-photo-view@1.0.0-beta.0.

**Comment by MinJieLiu** [comment]
你直接 npm install react-photo-view 就可以了

**Comment by MinJieLiu** [comment]
npm i react-photo-view@^1.0.0-beta.1

**Comment by MinJieLiu** [comment]
记得@后面不要加 v

**Comment by chenzhengWin** [comment]
$ npm i react-photo-view@^1.0.0-beta.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-photo-view@^1.0.0-beta.1.
$ npm i react-photo-view@1.0.0-beta.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-photo-view@1.0.0-beta.1.

加不加^,以及beta.0，beta.1都找不到呢

**Comment by MinJieLiu** [comment]
你换个项目再试试，可能受制于私有仓库的影响

**Comment by chenzhengWin** [comment]
你好啊，我换其他项目了，自己的项目，还是不行，默认install的还是0.5.7，指定版本的话还是找不到，郁闷。。。你那边其他项目操作过吗？
`npm view react-photo-view
`命令执行后是这样，npm找到的最新包还是先前的。日志如下：
react-photo-view@0.5.7 | MIT | deps: 2 | versions: 40
https://github.com/MinJieLiu/react-photo-view#readme

dist
.tarball: http://registry.npm.release.ctripcorp.com/react-photo-view/download/react-photo-view-0.5.7.tgz.shasum: 9048efddb06fe6583e24dbfed5c44209d3bd03f5

dependencies:
lodash.debounce: ^4.0.8 lodash.uniqueid: ^4.0.1 

maintainers:
- liumingyi <liumingyi_1@163.com>

dist-tags:
latest: 0.5.7  
published 4 months ago by liumingyi

**Comment by MinJieLiu** [comment]
```
npm view react-photo-view

react-photo-view@1.0.0-beta.1 | MIT | deps: none | versions: 42
一款精致的 React 的图片预览组件
https://github.com/MinJieLiu/react-photo-view#readme

keywords: react, react component, react photo, react-photo-view, photo, photo view, gallery

dist
.tarball: https://registry.npmjs.org/react-photo-view/-/react-photo-view-1.0.0-beta.1.tgz
.shasum: 959007e9f324b691b53004ca0e049bcf1257e874
.integrity: sha512-bUKpBvVt2tCfkM5qH0Tb1d7TfrjnoMJdsXpaxdT0wqkPVQ/SCoMCPt0Q6u6+bNSElJeXeADIqtX29C95EGkJdg==
.unpackedSize: 465.5 kB

maintainers:
- liumingyi <liumingyi_1@163.com>

dist-tags:
latest: 1.0.0-beta.1  

published 4 days ago by liumingyi <liumingyi_1@163.com>

```

**Comment by chenzhengWin** [comment]
OK，已解决。公司内网npm源未拉取到最新的npm包。更换npm源即可。谢谢作者！
