### ISSUE TITLE
新版本1.0.0-beta.1点击放大/缩小后，图片scale改变后会自动重新变成scale(1.0)

### ISSUE THREAD

**Issue by chenzhengWin** [MinJieLiu/react-photo-view#95]
class="PhotoView__Photo"
0.5x版：
```
transform: translate3d(0px, 0px, 0px) scale(2.8) rotate(0deg);
    transition: transform 0.5s cubic-bezier(0.25, 0.8, 0.25, 1) 0s;
```
新版：
宽高是根据缩放的，问题：transform的scale无论怎样，都自动变回了1
```
width: 748px;
    height: 544px;
    transform: translate3d(0px, 0px, 0px) scale(1) rotate(0deg);
    will-change: transform;
```

建议开发者用小图片测试一下，效果比较明显。（我暂时回退到0.5.7版本了。）
您有联系方式吗？方便交流

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/154208709-cf4f3eaf-2f28-43f7-afd6-b0bda30c1730.png)

**Comment by MinJieLiu** [comment]
在缩放结束后，应该修改当前图片的宽高为当前缩放的值，避免在不同情况的设备下出现因 scale 模糊的情况。

**Comment by chenzhengWin** [comment]
ok，移动端可能是那样，我试了下；我这边PC端的网页，用了个小图预览，几k的，放大后变形了。我先用上一个版本的，蒙层我自己加css处理了~

**Comment by MinJieLiu** [comment]
react-photo-view@1.0.0-beta.2
