### ISSUE TITLE
新版本1.0.0：建议只有一个图片的时候，不应该再出现左右箭头

### ISSUE THREAD

**Issue by chenzhengWin** [MinJieLiu/react-photo-view#96]
只有一个图片的时候，不应该再出现左右箭头。
这个老版本做的挺好，只有一个图片，不会显示出。

新版本的左右箭头要用 loop= false 控制不显示

**Comment by MinJieLiu** [comment]
这个我后面调整 loop API 将它支持控制最大数量出现 loop

**Comment by MinJieLiu** [comment]
react-photo-view@1.0.0-beta.2
 loop 支持指定数量开启
