### ISSUE TITLE
1.0.0-beta.3报错

### ISSUE THREAD

**Issue by scscms** [MinJieLiu/react-photo-view#98]
Server Error
Error: Must use import to load ES Module: D:\work\node_modules\react-photo-view\dist\react-photo-view.umd.js
require() of ES modules is not supported.
require() of D:\work\node_modules\react-photo-view\dist\react-photo-view.umd.js from D:\work\.next\server\pages\standard\scanCodeManagement\abnormalFeedbackRecord\recordDetail.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename react-photo-view.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\work\node_modules\react-photo-view\package.json.

**Comment by MinJieLiu** [comment]
这个问题已经修改尚未提交，你可以暂时 把 react-photo-view\package.json 中的 type: "module" 去掉，并吧 main 字段换成 "./dist/react-photo-view.cjs。

**Comment by scscms** [comment]
哈哈，不敢。因为最后还是要上容器化自动构建。只能暂时锁定旧版本。

**Comment by MinJieLiu** [comment]
那就稍微等等，周末时间才有时间，这周会提交

**Comment by MinJieLiu** [comment]
已发布
